application: roadmate
version: 1
runtime: python
api_version: 1

handlers:
# ----------------------------------------------------------------------------
# Static Directories
# ----------------------------------------------------------------------------
- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

# ----------------------------------------------------------------------------
# Dynamic Pages
# ----------------------------------------------------------------------------
- url: /
  script: pages/index.py

- url: /index\.html
  script: pages/index.py

- url: /support
  script: pages/support.py

- url: /about
  script: pages/about.py

- url: /profile(.*)
  script: pages/profile.py

- url: /edit_profile(.*)
  script: ajax/edit_handlers.py

- url: /browse_rides(.*)
  script: pages/browse.py

- url: /browse_riderequests(.*)
  script: pages/browse.py

- url: /location(.*)
  script: pages/location.py
  login: required

- url: /riderequest(.*)
  script: pages/riderequest.py

- url: /riderequest_create(.*)
  script: pages/riderequest.py
  login: required

- url: /ride(.*)
  script: pages/ride.py

- url: /ride_create(.*)
  script: pages/ride.py
  login: required

- url: /myrides(.*)
  script: pages/myrides.py
  login: required

- url: /mybookings(.*)
  script: pages/mybookings.py
  login: required

# ----------------------------------------------------------------------------
# AJAX Request Handlers
# ----------------------------------------------------------------------------
- url: /ajax/location-completer(.*)
  script: ajax/location-completer.py

- url: /ajax/edit_riderequest(.*)
  script: ajax/edit_handlers.py