application: roadmate
version: 1
runtime: python
api_version: 1

handlers:
# ----------------------------------------------------------------------------
# Static Directories
# ----------------------------------------------------------------------------
- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets

# ----------------------------------------------------------------------------
# Static Directories
# ----------------------------------------------------------------------------
- url: /
  script: pages/index.py
  
- url: /index\.html
  script: pages/index.py
  
- url: /support
  script: pages/support.py
  
- url: /about
  script: pages/about.py
  
- url: /user_profile
  script: pages/user_profile.py
  login: required
  
- url: /user_rides
  script: pages/user_rides.py
  login: required
